// packages/react/examples/react/src/App.jsx
import Canvas from '@antv/f2-react';
import { Chart, Interval, Axis, Legend, Timeline } from '@antv/f2';

const data = [
  [
    { genre: 'Sports', sold: 275 },
    { genre: 'Strategy', sold: 115 },
    { genre: 'Action', sold: 120 },
    { genre: 'Shooter', sold: 350 },
    { genre: 'Other', sold: 150 },
  ],
  [
    { genre: 'Sports', sold: 275 },
    { genre: 'Strategy', sold: 115 },
    { genre: 'Action', sold: 20 },
    { genre: 'Shooter', sold: 50 },
    { genre: 'Other', sold: 50 },
  ],
];

export default function App() {
  return (
    <div className="App">
      <Canvas pixelRatio={window.devicePixelRatio}>
        <Timeline delay={500}>
          {data.map((item, index) => {
            return (
              <Chart data={item} key={index}>
                <Legend />
                <Axis field="genre" />
                <Axis field="sold" />
                <Interval x="genre" y="sold" color="genre" />
              </Chart>
            );
          })}
        </Timeline>
      </Canvas>
    </div>
  );
}

// packages/vue/examples/vue3/src/App.vue
<script>
import { toRaw } from 'vue';
import Canvas from '@antv/f2-vue';
import { Chart, Interval, Axis } from '@antv/f2';
import Grahpic from './graphic';
import Legend from './legend';

const data1 = [
  { genre: 'Sports', sold: 275 },
  { genre: 'Strategy', sold: 115 },
  { genre: 'Action', sold: 120 },
  { genre: 'Shooter', sold: 350 },
  { genre: 'Other', sold: 150 },
];

const data2 = [
  { genre: 'Sports', sold: 275 },
  { genre: 'Strategy', sold: 115 },
  { genre: 'Action', sold: 20 },
  { genre: 'Shooter', sold: 50 },
  { genre: 'Other', sold: 50 },
];

export default {
  name: 'App',
  data() {
    return {
      year: '2021',
      chartData: data1,
    }
  },
  mounted() {
    setTimeout(() => {
      this.year = '2022';
      this.chartData = data2;
    }, 1000);
  },
  render() {
    const { year, chartData } = this;
    return (
      <div className="container">
        <Canvas pixelRatio={ window.devicePixelRatio }>
          <Chart data={ toRaw(chartData) }>
            <Grahpic year={ year } />
            <Legend />
            <Axis field="genre"/>
            <Axis field="sold"/>
            <Interval x="genre" y="sold" color="genre" />
          </Chart>
        </Canvas>
      </div>
    );
  },
};
</script>

<style>
.container {
  width: 500px;
  height: 300px;
}
</style>
